<font color="black" size="2">

  TYPECHO博客：<a href="http://fatmandj.mmkfc.com">FatManDJ</a>
  <br>
  主网站：<a href="https://www.fatdev.name">FatManDJ</a>
  <br>
  <img src="https://img.shields.io/badge/dynamic/json?color=black&label=GitHub&query=%24.data.totalSubs&url=https%3A%2F%2Fapi.spencerwoo.com%2Fsubstats%2F%3Fsource%3Dgithub%26queryKey%3DJiangYuShuo10023?style=for-the-badge&logo=github"></img>
  <img src="https://img.shields.io/badge/dynamic/json?color=blue&label=Zhihu&query=%24.data.totalSubs&url=https%3A%2F%2Fapi.spencerwoo.com%2Fsubstats%2F%3Fsource%3Dzhihu%26queryKey%3Dhello-world-95-18"></img>
</font>
